### PR TITLE
Responsive footer and fix img hover bug

### PR DESCRIPTION
**Pull request by MadhurbainKaur**

### CODE REVIEW

**Review by BrittanyMueller — CHANGES_REQUESTED** [review]
Looks good when it goes down to a single column, but during this in-between view size the questions card jumps off to the side like this.  Just tweak it so the sections are always centered in the footer.  
image

**Comment by MadhurbainKaur** [comment]
> Looks good when it goes down to a single column, but during this in-between view size the questions card jumps off to the side like this. Just tweak it so the sections are always centered in the footer. image

Didn't even notice, thanks! I will do that!

**Comment by easondan** [comment]
Looks good, One concern is that If the screen shrinks small enough the newsletter signup on the footer still overflows horizontally

Screen Shot 2022-03-13 at 3 13 20 PM

**Comment by BrittanyMueller** [comment]
Closing this PR because the changes were brought in already outside of this

**Pull request closed without merging**
